### PR TITLE
add more boats

### PR DESCRIPTION
**Pull request by connyay**

### CODE REVIEW

**Comment by connyay** [comment]
@matthauck @coleGillespie pls review

**Comment by matthauck** [comment]
more boats!!

**Comment by matthauck** [comment]
```
             |    |    |
             )_)  )_)  )_)
            )___))___))___)\
           )____)____)_____)\\
         _____|____|____|____\\\__
---------\                   /---------
  ^^^^^ ^^^^^^^^^^^^^^^^^^^^^
    ^^^^      ^^^^     ^^^    ^^
         ^^^^      ^^^
```
```
    __|__ |___| |\
    |o__| |___| | \
    |___| |___| |o \
   _|___| |___| |__o\
  /...\_____|___|____\_/
  \   o * o * * o o  /
~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
               /|___
             ///|   ))
           /////|   )))
         ///////|    )))
       /////////|     )))
     ///////////|     ))))
   /////////////|     )))
  //////////////|    )))
////////////////|___)))
  ______________|________
  \                    /
~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by matthauck** [comment]
```
         /|\
       /__| )
     /____| ))
   /______| )))
 /________|  )))
         _|____))
 \======| o o /
```

```
```

**Comment by matthauck** [comment]
```
             /|~~~
           ///|
         /////|
       ///////|
     /////////|
   \==========|===/
```

```
```

**Comment by cole-gillespie** [comment]
im confused why the boats have lines in them

**Comment by cole-gillespie** [comment]
```
```

```
```

**Comment by cole-gillespie** [comment]
tilde equals white lines in md ?

**Pull request merged**
